export interface Herb {
  id: string;
  name: string;
  scientificName: string;
  category: string;
  description: string;
  benefits: string[];
  usage: string;
  precautions: string;
  image: string;
  scientificBacking?: string;
}

export const HERBS: Herb[] = [
  {
    id: '1',
    name: 'Turmeric',
    scientificName: 'Curcuma longa',
    category: 'Anti-inflammatory',
    description: 'Turmeric is a flowering plant of the ginger family. Its roots are used in cooking and traditional medicine for their powerful anti-inflammatory properties.',
    benefits: ['Reduces inflammation', 'Powerful antioxidant', 'Boosts brain function', 'May lower risk of heart disease'],
    usage: 'Commonly consumed as a spice in foods or as a supplement. Turmeric tea is also popular.',
    precautions: 'High doses can act as a blood thinner. Use with caution before surgery.',
    image: 'https://images.unsplash.com/photo-1615485290382-441e4d0c9cb5?q=80&w=800&auto=format&fit=crop',
    scientificBacking: 'Curcumin, the active compound in turmeric, has been shown in multiple clinical trials to have potent anti-inflammatory effects comparable to some anti-inflammatory drugs, but without the side effects.',
  },
  {
    id: '2',
    name: 'Ginger',
    scientificName: 'Zingiber officinale',
    category: 'Digestive',
    description: 'Ginger is a widely used spice and medicinal herb known for its spicy aroma and its ability to soothe digestive issues.',
    benefits: ['Relieves nausea', 'Aids digestion', 'Reduces muscle pain', 'Lower blood sugar'],
    usage: 'Can be used fresh, dried, powdered, or as an oil or juice.',
    precautions: 'May cause mild side effects like heartburn or diarrhea if consumed in excess.',
    image: 'https://images.unsplash.com/photo-1599940824399-b87987ceb72a?q=80&w=800&auto=format&fit=crop',
    scientificBacking: 'Studies indicate that ginger can accelerate emptying of the stomach, which can be beneficial for people with indigestion and related stomach discomfort.',
  },
  {
    id: '3',
    name: 'Peppermint',
    scientificName: 'Mentha piperita',
    category: 'Digestive',
    description: 'Peppermint is a hybrid mint, a cross between watermint and spearmint. It is widely used for its cooling sensation and digestive benefits.',
    benefits: ['Relieves digestive symptoms', 'Reduces headaches', 'Improves focus', 'Clears sinuses'],
    usage: 'Often consumed as tea or used as an essential oil.',
    precautions: 'May worsen GERD or acid reflux in some individuals.',
    image: 'https://images.unsplash.com/photo-1626700051175-6818013e184f?q=80&w=800&auto=format&fit=crop',
    scientificBacking: 'Research shows that peppermint oil is effective at improving symptoms of Irritable Bowel Syndrome (IBS) by relaxing the smooth muscles in the colon.',
  },
  {
    id: '4',
    name: 'Echinacea',
    scientificName: 'Echinacea purpurea',
    category: 'Immune Support',
    description: 'Echinacea is a group of flowering plants in the daisy family, widely used as an herbal remedy to prevent or treat the common cold.',
    benefits: ['Boosts immune system', 'Reduces cold duration', 'Anti-inflammatory', 'Antioxidant properties'],
    usage: 'Usually taken as a tea, juice, or supplement at the first sign of a cold.',
    precautions: 'People with autoimmune disorders should consult a doctor before use.',
    image: 'https://images.unsplash.com/photo-1596708027732-261ba1019036?q=80&w=800&auto=format&fit=crop',
    scientificBacking: 'A review of 14 studies found that echinacea may lower the risk of developing colds by more than 50% and shorten the duration of colds by one and a half days.',
  },
  {
    id: '5',
    name: 'Lavender',
    scientificName: 'Lavandula angustifolia',
    category: 'Calming',
    description: 'Lavender is a versatile herb known for its beautiful scent and its ability to promote relaxation and sleep.',
    benefits: ['Reduces anxiety', 'Improves sleep quality', 'Soothes skin irritations', 'Alleviates headaches'],
    usage: 'Used in aromatherapy, as tea, or applied topically as an essential oil.',
    precautions: 'Essential oil should be diluted before topical application.',
    image: 'https://images.unsplash.com/photo-1471943311424-646960669fba?q=80&w=800&auto=format&fit=crop',
    scientificBacking: 'Clinical evidence suggests that lavender oil can be as effective as some pharmaceutical anti-anxiety medications in reducing symptoms of generalized anxiety disorder.',
  },
  {
    id: '6',
    name: 'Ginseng',
    scientificName: 'Panax ginseng',
    category: 'Energy',
    description: 'Ginseng is a root known for its adaptogenic properties, helping the body manage stress and boost energy levels.',
    benefits: ['Increases energy', 'Reduces stress', 'Improves cognitive function', 'Anti-inflammatory'],
    usage: 'Can be eaten raw, steamed, or taken as an extract or supplement.',
    precautions: 'May interfere with certain medications, including blood thinners and diabetes drugs.',
    image: 'https://images.unsplash.com/photo-1627830601323-95696d5a11c1?q=80&w=800&auto=format&fit=crop',
    scientificBacking: 'Studies have shown that Panax ginseng can help reduce fatigue and increase physical activity by lowering oxidative damage and increasing energy production in cells.',
  },
  {
    id: '7',
    name: 'Chamomile',
    scientificName: 'Matricaria chamomilla',
    category: 'Calming',
    description: 'Chamomile is one of the most ancient medicinal herbs known to mankind. It is famous for its mild sedative properties.',
    benefits: ['Promotes sleep', 'Reduces anxiety', 'Aids digestion', 'Soothes skin'],
    usage: 'Most commonly consumed as a herbal tea.',
    precautions: 'People with severe allergies to daisies or ragweed should use with caution.',
    image: 'https://images.unsplash.com/photo-1515699503431-22bbf5ef1118?q=80&w=800&auto=format&fit=crop',
    scientificBacking: 'Research has shown that chamomile extract can significantly improve sleep quality in elderly adults and reduce symptoms of generalized anxiety disorder.',
  },
  {
    id: '8',
    name: 'Holy Basil',
    scientificName: 'Ocimum tenuiflorum',
    category: 'Adaptogen',
    description: 'Also known as Tulsi, Holy Basil is a sacred plant in India, prized for its ability to help the body adapt to stress.',
    benefits: ['Reduces stress and anxiety', 'Supports heart health', 'Boosts immunity', 'Anti-inflammatory'],
    usage: 'Leaves can be used fresh in cooking or brewed as a tea.',
    precautions: 'May lower blood sugar; use caution if taking diabetes medication.',
    image: 'https://images.unsplash.com/photo-1614735241165-6756e1df61ab?q=80&w=800&auto=format&fit=crop',
    scientificBacking: 'Clinical studies suggest that Holy Basil has anti-anxiety and anti-depressant properties, comparable to diazepam and antidepressant drugs.',
  },
  {
    id: '9',
    name: 'Rosemary',
    scientificName: 'Salvia rosmarinus',
    category: 'Cognitive',
    description: 'Rosemary is a fragrant evergreen herb native to the Mediterranean. It is used as a culinary spice and for its potential to improve memory.',
    benefits: ['Improves memory and focus', 'Rich in antioxidants', 'Supports digestion', 'Hair growth'],
    usage: 'Used fresh or dried in cooking, or as an essential oil.',
    precautions: 'In large amounts, may cause vomiting or skin sensitivity.',
    image: 'https://images.unsplash.com/photo-1515471209610-dae1c9a581c5?q=80&w=800&auto=format&fit=crop',
    scientificBacking: 'Exposure to rosemary aroma has been found to improve performance in cognitive tasks, specifically memory speed and accuracy.',
  },
  {
    id: '10',
    name: 'Ashwagandha',
    scientificName: 'Withania somnifera',
    category: 'Adaptogen',
    description: 'Ashwagandha is an ancient medicinal herb classified as an adaptogen, which means it can help your body manage stress.',
    benefits: ['Reduces stress and anxiety', 'Improves strength', 'Boosts brain function', 'Lowers blood sugar'],
    usage: 'Usually taken in powder form mixed with water or milk, or as a supplement.',
    precautions: 'Not recommended for pregnant women or people with thyroid conditions without medical advice.',
    image: 'https://images.unsplash.com/photo-1611689342806-0863700ce1e4?q=80&w=800&auto=format&fit=crop',
    scientificBacking: 'In a study of 64 people with chronic stress, those who supplemented with ashwagandha reported a 69% average reduction in anxiety and insomnia, compared to 11% in the placebo group.',
  },
  {
    id: '11',
    name: 'Milk Thistle',
    scientificName: 'Silybum marianum',
    category: 'Liver Health',
    description: 'Milk thistle is a flowering herb related to the daisy and ragweed family. It is best known for its potential to protect the liver.',
    benefits: ['Protects liver function', 'Supports skin health', 'Reduces cholesterol', 'May support weight loss'],
    usage: 'Commonly taken as a standardized extract in capsule form.',
    precautions: 'Can cause allergic reactions in people sensitive to the Asteraceae family.',
    image: 'https://images.unsplash.com/photo-1635345753049-598914b13867?q=80&w=800&auto=format&fit=crop',
    scientificBacking: 'The active ingredient, silymarin, acts as an antioxidant by reducing free radical production and creating a toxin-blocking effect in the liver.',
  },
  {
    id: '12',
    name: 'Valerian Root',
    scientificName: 'Valeriana officinalis',
    category: 'Sleep',
    description: 'Valerian is a herb native to Europe and parts of Asia. Its root has been used since ancient times to promote sleep and reduce anxiety.',
    benefits: ['Improves sleep quality', 'Reduces anxiety', 'Promotes relaxation', 'May help with PMS symptoms'],
    usage: 'Usually taken as a tea or supplement shortly before bedtime.',
    precautions: 'May cause vivid dreams or morning grogginess in some users.',
    image: 'https://images.unsplash.com/photo-1628151015968-3a4429e9ef04?q=80&w=800&auto=format&fit=crop',
    scientificBacking: 'A systematic review found that valerian can improve sleep quality without the side effects associated with conventional sleep medications.',
  },
  {
    id: '13',
    name: 'Aloe Vera',
    scientificName: 'Aloe barbadensis miller',
    category: 'Skin Health',
    description: 'Aloe vera is a succulent plant species known for its thick, fleshy green leaves containing a gel used for various medicinal purposes.',
    benefits: ['Soothes burns', 'Heals skin irritations', 'Hydrates skin', 'Digestive support (if ingested properly)'],
    usage: 'Gel is applied topically to skin; juice can be consumed with caution.',
    precautions: 'Ingesting whole-leaf extract can be toxic; only consume food-grade products.',
    image: 'https://images.unsplash.com/photo-1596040033229-a9821ebd058d?q=80&w=800&auto=format&fit=crop',
    scientificBacking: 'Clinical studies show that topical aloe vera can shorten the healing time of first and second-degree burns by about 9 days compared to conventional treatment.',
  },
  {
    id: '14',
    name: 'Garlic',
    scientificName: 'Allium sativum',
    category: 'Immune Support',
    description: 'Garlic is a species in the onion genus, used globally for its pungent flavor and numerous health-promoting properties.',
    benefits: ['Supports heart health', 'Boosts immunity', 'Lower blood pressure', 'Antimicrobial properties'],
    usage: 'Can be eaten raw, cooked, or taken as an aged extract.',
    precautions: 'May increase bleeding risk; consult doctor before surgery.',
    image: 'https://images.unsplash.com/photo-1540148426945-6cf22a6b2383?q=80&w=800&auto=format&fit=crop',
    scientificBacking: 'Garlic supplements are known to have a significant impact on reducing blood pressure in people with high blood pressure, sometimes as effective as standard medications.',
  },
  {
    id: '15',
    name: 'Ginkgo Biloba',
    scientificName: 'Ginkgo biloba',
    category: 'Cognitive',
    description: 'Ginkgo is one of the oldest living tree species. Most ginkgo products are made with extract prepared from its fan-shaped leaves.',
    benefits: ['Improves circulation', 'Supports memory', 'Antioxidant', 'Reduces anxiety'],
    usage: 'Available in capsules, tablets, or liquid extracts.',
    precautions: 'Interacts with blood thinners like warfarin and aspirin.',
    image: 'https://images.unsplash.com/photo-1589146188851-96f3ccf8c372?q=80&w=800&auto=format&fit=crop',
    scientificBacking: 'Ginkgo has been repeatedly studied for its ability to reduce anxiety, stress, and other symptoms associated with Alzheimer’s disease and age-related cognitive decline.',
  },
  {
    id: '16',
    name: 'St. Johns Wort',
    scientificName: 'Hypericum perforatum',
    category: 'Mood Support',
    description: 'St. Johns wort is a flowering plant that has been used for centuries for mental health conditions.',
    benefits: ['Alleviates depression', 'Reduces menopause symptoms', 'Anti-inflammatory', 'Soothes skin (topical)'],
    usage: 'Often taken as a tea, capsule, or liquid extract.',
    precautions: 'Interacts with a wide range of medications, including birth control and antidepressants.',
    image: 'https://images.unsplash.com/photo-1628151016021-3965a9e33431?q=80&w=800&auto=format&fit=crop',
    scientificBacking: 'Several studies support the use of St. Johns wort for treating mild-to-moderate depression, showing it to be more effective than a placebo.',
  },
  {
    id: '17',
    name: 'Dandelion',
    scientificName: 'Taraxacum officinale',
    category: 'Digestive',
    description: 'Often considered a weed, the dandelion has a long history of use in traditional medicine to support liver and digestive health.',
    benefits: ['Diuretic properties', 'Supports liver health', 'Rich in antioxidants', 'May lower blood pressure'],
    usage: 'Leaves can be used in salads; roots can be roasted as a coffee substitute.',
    precautions: 'People with gallbladder issues should avoid dandelion.',
    image: 'https://images.unsplash.com/photo-1500382017468-9049fed747ef?q=80&w=800&auto=format&fit=crop',
    scientificBacking: 'Traditional use of dandelion as a diuretic is supported by its high potassium content, which can help increase urine production.',
  },
  {
    id: '18',
    name: 'Fenugreek',
    scientificName: 'Trigonella foenum-graecum',
    category: 'Metabolic Support',
    description: 'Fenugreek is an herb similar to clover. Its seeds are used in cooking, in medicine, and to hide the taste of other medicine.',
    benefits: ['Regulates blood sugar', 'Boosts testosterone', 'Increases milk production', 'Reduces appetite'],
    usage: 'Seeds can be eaten, brewed as tea, or taken as a supplement.',
    precautions: 'Can cause a "maple syrup" odor in sweat and urine.',
    image: 'https://images.unsplash.com/photo-1591122605556-94646700593b?q=80&w=800&auto=format&fit=crop',
    scientificBacking: 'Studies have demonstrated that fenugreek seeds can improve glucose tolerance and lower blood sugar levels in both type 1 and type 2 diabetes.',
  },
  {
    id: '19',
    name: 'Maca Root',
    scientificName: 'Lepidium meyenii',
    category: 'Energy',
    description: 'Maca is a plant that grows in the Andes mountains of Peru. It is a cruciferous vegetable, related to broccoli and kale.',
    benefits: ['Boosts libido', 'Increases energy', 'Improves mood', 'Reduces menopause symptoms'],
    usage: 'Usually consumed as a powder added to smoothies, oatmeal, or baked goods.',
    precautions: 'People with thyroid issues should be cautious due to goitrogens.',
    image: 'https://images.unsplash.com/photo-1622484211148-7163014aa0c4?q=80&w=800&auto=format&fit=crop',
    scientificBacking: 'Evidence suggests that maca can improve sexual desire in both men and women after six weeks of use.',
  },
  {
    id: '20',
    name: 'Passionflower',
    scientificName: 'Passiflora incarnata',
    category: 'Calming',
    description: 'Passionflower is a climbing vine native to the southeastern United States and Central and South America.',
    benefits: ['Reduces anxiety', 'Improves sleep', 'Soothes nervous system', 'May help with ADHD'],
    usage: 'Available as tea, tinctures, and tablets.',
    precautions: 'Should not be used during pregnancy as it may induce contractions.',
    image: 'https://images.unsplash.com/photo-1533421160395-886ecf1309d9?q=80&w=800&auto=format&fit=crop',
    scientificBacking: 'Clinical trials suggest that passionflower is as effective as oxazepam for treating symptoms of generalized anxiety disorder, with fewer sedative side effects.',
  },
  {
    id: '21',
    name: 'Saw Palmetto',
    scientificName: 'Serenoa repens',
    category: 'Mens Health',
    description: 'Saw palmetto is a type of palm tree. Its fruit is used to make medicine.',
    benefits: ['Supports prostate health', 'Reduces hair loss', 'Improves urinary function', 'Decreases inflammation'],
    usage: 'Typically taken in capsule form as a standardized extract.',
    precautions: 'May interfere with birth control and blood thinners.',
    image: 'https://images.unsplash.com/photo-1501747315-124a0eaca060?q=80&w=800&auto=format&fit=crop',
    scientificBacking: 'Some research suggests that saw palmetto can help treat Benign Prostatic Hyperplasia (BPH) by blocking the enzyme that converts testosterone into DHT.',
  },
  {
    id: '22',
    name: 'Elderberry',
    scientificName: 'Sambucus nigra',
    category: 'Immune Support',
    description: 'Elderberry refers to several varieties of the Sambucus tree. The most common is the European elderberry or black elderberry.',
    benefits: ['Shortens flu duration', 'Rich in antioxidants', 'Supports heart health', 'Fights inflammation'],
    usage: 'Commonly taken as a syrup, gummy, or lozenge.',
    precautions: 'Raw berries, bark, and leaves are toxic and can cause severe stomach upset.',
    image: 'https://images.unsplash.com/photo-1563212891-9e7323863456?q=80&w=800&auto=format&fit=crop',
    scientificBacking: 'A study found that people who took elderberry syrup 4 times a day for 5 days saw their flu symptoms clear up 4 days earlier than those who took a placebo.',
  },
  {
    id: '23',
    name: 'Oregano Oil',
    scientificName: 'Origanum vulgare',
    category: 'Antimicrobial',
    description: 'Oregano is a fragrant herb. Oregano oil is the concentrated extract of the plant.',
    benefits: ['Fights bacteria', 'Antifungal properties', 'Reduces inflammation', 'Antioxidant effects'],
    usage: 'Used topically (diluted) or taken in capsules.',
    precautions: 'Very potent; can irritate skin and mucous membranes if not diluted.',
    image: 'https://images.unsplash.com/photo-1533282960533-51328aa49826?q=80&w=800&auto=format&fit=crop',
    scientificBacking: 'Carvacrol, the main compound in oregano oil, has been shown to be effective against several types of bacteria, including some that are resistant to antibiotics.',
  },
  {
    id: '24',
    name: 'Nettle',
    scientificName: 'Urtica dioica',
    category: 'Anti-inflammatory',
    description: 'Also known as stinging nettle, this plant has been used for centuries for its nutritional and medicinal properties.',
    benefits: ['Relieves allergies', 'Reduces joint pain', 'Supports prostate health', 'Lower blood pressure'],
    usage: 'Leaves can be cooked, dried for tea, or taken as a supplement.',
    precautions: 'Can cause skin irritation if handled raw without gloves.',
    image: 'https://images.unsplash.com/photo-1597843786271-29007421888e?q=80&w=800&auto=format&fit=crop',
    scientificBacking: 'Nettle extract has been found to inhibit the inflammation that triggers seasonal allergies, effectively acting as a natural antihistamine.',
  },
  {
    id: '25',
    name: 'Rhodiola Rosea',
    scientificName: 'Rhodiola rosea',
    category: 'Adaptogen',
    description: 'Rhodiola is an herb that grows in the cold, mountainous regions of Europe and Asia. It is used as an adaptogen.',
    benefits: ['Reduces fatigue', 'Improves brain function', 'Enhances exercise performance', 'Helps manage stress'],
    usage: 'Usually taken in pill or capsule form.',
    precautions: 'May cause dry mouth or dizziness in some people.',
    image: 'https://images.unsplash.com/photo-1628151016021-3965a9e33431?q=80&w=800&auto=format&fit=crop',
    scientificBacking: 'In a study of 101 people with stress-related fatigue, taking 400mg of rhodiola daily for four weeks significantly improved symptoms of exhaustion and anxiety.',
  },
  {
    id: '26',
    name: 'Astragalus',
    scientificName: 'Astragalus propinquus',
    category: 'Immune Support',
    description: 'Astragalus is a root used in Traditional Chinese Medicine for thousands of years to strengthen the "Wei Qi" or protective energy.',
    benefits: ['Boosts immune system', 'Anti-aging properties', 'Supports heart health', 'Reduces fatigue'],
    usage: 'Root is sliced and simmered in soups or taken as a tincture/capsule.',
    precautions: 'May interact with immunosuppressant drugs.',
    image: 'https://images.unsplash.com/photo-1596708027732-261ba1019036?q=80&w=800&auto=format&fit=crop',
    scientificBacking: 'Evidence suggests astragalus can increase the body’s production of white blood cells, which are responsible for preventing illness.',
  },
  {
    id: '27',
    name: 'Bacopa Monnieri',
    scientificName: 'Bacopa monnieri',
    category: 'Cognitive',
    description: 'Bacopa, also known as Brahmi, is a staple herb in Ayurvedic medicine used for cognitive enhancement.',
    benefits: ['Improves memory', 'Reduces anxiety', 'Antioxidant', 'May lower blood pressure'],
    usage: 'Usually taken as a powder or extract with a fat source to improve absorption.',
    precautions: 'May cause digestive upset or nausea if taken on an empty stomach.',
    image: 'https://images.unsplash.com/photo-1626700051175-6818013e184f?q=80&w=800&auto=format&fit=crop',
    scientificBacking: 'Studies show that Bacopa monnieri can improve spatial learning and retain information by enhancing the communication between neurons.',
  },
  {
    id: '28',
    name: 'Cranberry',
    scientificName: 'Vaccinium macrocarpon',
    category: 'Urinary Health',
    description: 'Cranberries are small, red berries that are packed with nutrients and antioxidant compounds.',
    benefits: ['Prevents UTIs', 'Supports digestive health', 'Rich in Vitamin C', 'Heart health'],
    usage: 'Consumed as juice, dried fruit, or concentrated capsules.',
    precautions: 'Large amounts of juice can lead to stomach upset or diarrhea.',
    image: 'https://images.unsplash.com/photo-1596392934005-7f31e3d36802?q=80&w=800&auto=format&fit=crop',
    scientificBacking: 'Proanthocyanidins in cranberries prevent E. coli bacteria from sticking to the lining of the bladder and urinary tract, preventing infection.',
  },
  {
    id: '29',
    name: 'Gotu Kola',
    scientificName: 'Centella asiatica',
    category: 'Cognitive',
    description: 'Gotu kola is known as the "herb of longevity" in Asian medicine, used to boost brainpower and heal skin.',
    benefits: ['Improves cognition', 'Reduces anxiety', 'Heals wounds', 'Supports vein health'],
    usage: 'Leaves are eaten fresh, dried for tea, or used as a topical cream.',
    precautions: 'May cause liver sensitivity in rare cases if taken in high doses for a long period.',
    image: 'https://images.unsplash.com/photo-1515471209610-dae1c9a581c5?q=80&w=800&auto=format&fit=crop',
    scientificBacking: 'Research indicates that Gotu Kola can increase nerve growth factor (NGF) which helps in the maintenance and growth of neurons.',
  },
  {
    id: '30',
    name: 'Hawthorn',
    scientificName: 'Crataegus',
    category: 'Heart Health',
    description: 'Hawthorn berries, leaves, and flowers have been used for heart problems since the first century.',
    benefits: ['Improves blood flow', 'Lower blood pressure', 'Reduces chest pain', 'Antioxidant'],
    usage: 'Available as tea, capsules, or liquid extracts.',
    precautions: 'Can interact with many heart medications; consult a doctor first.',
    image: 'https://images.unsplash.com/photo-1540148426945-6cf22a6b2383?q=80&w=800&auto=format&fit=crop',
    scientificBacking: 'Studies suggest hawthorn can improve heart function and exercise tolerance in people with mild-to-moderate heart failure.',
  },
  {
    id: '31',
    name: 'Kava Kava',
    scientificName: 'Piper methysticum',
    category: 'Calming',
    description: 'Kava is a root from the South Pacific islands, known for its powerful relaxing effects.',
    benefits: ['Reduces severe anxiety', 'Promotes sleep', 'Relaxes muscles', 'Social lubricant'],
    usage: 'Traditionally prepared as a drink from the ground root.',
    precautions: 'Heavy use has been linked to liver damage; use with extreme caution.',
    image: 'https://images.unsplash.com/photo-1628151015968-3a4429e9ef04?q=80&w=800&auto=format&fit=crop',
    scientificBacking: 'Evidence shows that kava is effective at treating symptoms of anxiety and is comparable to some prescription benzodiazepines.',
  },
  {
    id: '32',
    name: 'Licorice Root',
    scientificName: 'Glycyrrhiza glabra',
    category: 'Digestive',
    description: 'Licorice root is one of the world’s oldest herbal remedies, used to treat various ailments and flavor foods.',
    benefits: ['Soothes sore throat', 'Aids acid reflux', 'Anti-inflammatory', 'Antiviral properties'],
    usage: 'Used as tea, chewable tablets, or liquid extract.',
    precautions: 'Can cause high blood pressure and low potassium if used in excess.',
    image: 'https://images.unsplash.com/photo-1515699503431-22bbf5ef1118?q=80&w=800&auto=format&fit=crop',
    scientificBacking: 'Licorice root extract is often used to treat stomach ulcers and is known to increase the production of protective mucus in the stomach.',
  },
  {
    id: '33',
    name: 'Marshmallow Root',
    scientificName: 'Althaea officinalis',
    category: 'Respiratory',
    description: 'Not the candy! The marshmallow plant has a high mucilage content used to coat and soothe irritated tissues.',
    benefits: ['Relieves dry cough', 'Soothes sore throat', 'Aids digestive lining', 'Heals skin'],
    usage: 'Best prepared as a cold infusion (tea) to extract the mucilage.',
    precautions: 'May slow the absorption of other medications taken at the same time.',
    image: 'https://images.unsplash.com/photo-1596040033229-a9821ebd058d?q=80&w=800&auto=format&fit=crop',
    scientificBacking: 'The mucilage in marshmallow root acts as a protective layer for the throat and stomach, reducing irritation and inflammation.',
  },
  {
    id: '34',
    name: 'Mullein',
    scientificName: 'Verbascum thapsus',
    category: 'Respiratory',
    description: 'Mullein is a versatile plant used for centuries to treat respiratory conditions like asthma and bronchitis.',
    benefits: ['Expectorant properties', 'Reduces lung inflammation', 'Fights ear infections (oil)', 'Antiviral'],
    usage: 'Leaves and flowers are used in teas; oil is used for ear drops.',
    precautions: 'Fine hairs on leaves can irritate the throat if not strained properly from tea.',
    image: 'https://images.unsplash.com/photo-1500382017468-9049fed747ef?q=80&w=800&auto=format&fit=crop',
    scientificBacking: 'Mullein contains saponins, which help thin and expel mucus from the lungs, making it a classic remedy for congestion.',
  },
  {
    id: '35',
    name: 'Olive Leaf',
    scientificName: 'Olea europaea',
    category: 'Immune Support',
    description: 'Olive leaf extract is derived from the leaves of the olive tree, containing high levels of oleuropein.',
    benefits: ['Antiviral', 'Lower blood pressure', 'Supports heart health', 'Blood sugar regulation'],
    usage: 'Usually taken as a liquid extract or in capsule form.',
    precautions: 'May interact with blood pressure and diabetes medications.',
    image: 'https://images.unsplash.com/photo-1533282960533-51328aa49826?q=80&w=800&auto=format&fit=crop',
    scientificBacking: 'The compound oleuropein has been shown to have potent antimicrobial and antiviral activity, effective against a wide range of pathogens.',
  },
  {
    id: '36',
    name: 'Raspberry Leaf',
    scientificName: 'Rubus idaeus',
    category: 'Womens Health',
    description: 'Red raspberry leaf is often called the "woman’s herb" due to its benefits for reproductive health.',
    benefits: ['Tones the uterus', 'Relieves PMS', 'Shortens labor', 'Rich in iron and magnesium'],
    usage: 'Most commonly consumed as a herbal tea.',
    precautions: 'Should only be used in the second and third trimesters of pregnancy under supervision.',
    image: 'https://images.unsplash.com/photo-1515471209610-dae1c9a581c5?q=80&w=800&auto=format&fit=crop',
    scientificBacking: 'A study showed that women who drank red raspberry leaf tea had shorter second stages of labor and a reduced need for forceps during delivery.',
  },
  {
    id: '37',
    name: 'Saffron',
    scientificName: 'Crocus sativus',
    category: 'Mood Support',
    description: 'Saffron is the world’s most expensive spice, harvested from the stigmas of the autumn crocus.',
    benefits: ['Improves mood', 'Reduces PMS symptoms', 'Antioxidant', 'Supports eye health'],
    usage: 'A small amount added to food or taken as an extract.',
    precautions: 'Extremely high doses can be toxic; stick to culinary or recommended supplement levels.',
    image: 'https://images.unsplash.com/photo-1599940824399-b87987ceb72a?q=80&w=800&auto=format&fit=crop',
    scientificBacking: 'Research has shown that saffron is as effective as fluoxetine (Prozac) in treating mild-to-moderate depression.',
  },
  {
    id: '38',
    name: 'Slippery Elm',
    scientificName: 'Ulmus rubra',
    category: 'Digestive',
    description: 'The inner bark of the slippery elm tree becomes a "slick" gel when mixed with water, coating the digestive tract.',
    benefits: ['Soothes IBS', 'Relieves sore throat', 'Aids acid reflux', 'Heals skin (topical)'],
    usage: 'Powdered bark is mixed with water to form a gruel or taken as a lozenge.',
    precautions: 'May interfere with the absorption of other oral medications.',
    image: 'https://images.unsplash.com/photo-1515699503431-22bbf5ef1118?q=80&w=800&auto=format&fit=crop',
    scientificBacking: 'Slippery elm stimulates nerve endings in the GI tract to increase mucus secretion, which helps protect against ulcers and excess acidity.',
  },
  {
    id: '39',
    name: 'Uva Ursi',
    scientificName: 'Arctostaphylos uva-ursi',
    category: 'Urinary Health',
    description: 'Uva Ursi, or Bearberry, is a traditional remedy for urinary tract infections.',
    benefits: ['Fights UTIs', 'Reduces bloating', 'Anti-inflammatory', 'Antiseptic properties'],
    usage: 'Taken as a tea or tincture for short periods of time.',
    precautions: 'Should not be taken for more than a week; high doses can be toxic to the liver.',
    image: 'https://images.unsplash.com/photo-1500382017468-9049fed747ef?q=80&w=800&auto=format&fit=crop',
    scientificBacking: 'The compound arbutin in Uva Ursi is converted to hydroquinone in the urine, which has powerful antiseptic properties that kill bacteria.',
  },
  {
    id: '40',
    name: 'Wild Yam',
    scientificName: 'Dioscorea villosa',
    category: 'Womens Health',
    description: 'Wild yam root has been used for centuries to treat hormonal issues and digestive disorders.',
    benefits: ['Balances hormones', 'Relieves menstrual cramps', 'Antispasmodic', 'Gallbladder support'],
    usage: 'Available as a topical cream or internal supplement.',
    precautions: 'Should not be used by those with hormone-sensitive conditions like breast cancer.',
    image: 'https://images.unsplash.com/photo-1596040033229-a9821ebd058d?q=80&w=800&auto=format&fit=crop',
    scientificBacking: 'Contains diosgenin, a precursor that is used in the laboratory to produce various steroids like estrogen and DHEA.',
  },
  {
    id: '41',
    name: 'Yellow Dock',
    scientificName: 'Rumex crispus',
    category: 'Detox',
    description: 'Yellow dock is a common weed with a long yellow taproot used to cleanse the blood and support the liver.',
    benefits: ['Iron-rich', 'Supports liver detox', 'Mild laxative', 'Clears skin issues'],
    usage: 'Tincture or decoction of the root.',
    precautions: 'High in oxalates; avoid if prone to kidney stones.',
    image: 'https://images.unsplash.com/photo-1533282960533-51328aa49826?q=80&w=800&auto=format&fit=crop',
    scientificBacking: 'Traditional use for iron-deficiency anemia is supported by its ability to help the body absorb iron from other sources.',
  },
  {
    id: '42',
    name: 'Yerba Mate',
    scientificName: 'Ilex paraguariensis',
    category: 'Energy',
    description: 'Yerba mate is a traditional South American drink that provides a clean energy boost without the jitters.',
    benefits: ['Mental clarity', 'Fat burning', 'Antioxidant-rich', 'Improves digestion'],
    usage: 'Brewed as a tea and often shared socially.',
    precautions: 'High caffeine content; avoid if sensitive to stimulants.',
    image: 'https://images.unsplash.com/photo-1515471209610-dae1c9a581c5?q=80&w=800&auto=format&fit=crop',
    scientificBacking: 'Contains xanthines (like caffeine), which are known to improve focus, mood, and alertness by blocking adenosine receptors in the brain.',
  },
  {
    id: '43',
    name: 'Schisandra',
    scientificName: 'Schisandra chinensis',
    category: 'Adaptogen',
    description: 'Known as "five-flavor fruit," schisandra supports the liver, skin, and nervous system.',
    benefits: ['Protects liver', 'Increases endurance', 'Mental performance', 'Anti-aging'],
    usage: 'Berries are used in teas, tinctures, or powders.',
    precautions: 'May increase stomach acid; use with caution if you have ulcers or GERD.',
    image: 'https://images.unsplash.com/photo-1599940824399-b87987ceb72a?q=80&w=800&auto=format&fit=crop',
    scientificBacking: 'Schisandrins in the fruit have been found to prevent liver damage and stimulate liver repair after toxin exposure.',
  },
  {
    id: '44',
    name: 'Reishi Mushroom',
    scientificName: 'Ganoderma lucidum',
    category: 'Immune Support',
    description: 'Known as the "mushroom of immortality," reishi is a powerful tonic for the immune system and stress management.',
    benefits: ['Immune modulator', 'Reduces anxiety', 'Anti-tumor properties', 'Supports heart health'],
    usage: 'Usually taken as an extract, powder, or decoction (tea).',
    precautions: 'Can have blood-thinning effects; avoid before surgery.',
    image: 'https://images.unsplash.com/photo-1596708027732-261ba1019036?q=80&w=800&auto=format&fit=crop',
    scientificBacking: 'Contains beta-glucans and triterpenes that have been shown to enhance the activity of natural killer (NK) cells.',
  },
  {
    id: '45',
    name: 'Lion’s Mane',
    scientificName: 'Hericium erinaceus',
    category: 'Cognitive',
    description: 'A unique mushroom that looks like a white shaggy mane, famous for its ability to regenerate brain cells.',
    benefits: ['Brain health', 'Nerve regeneration', 'Mood support', 'Focus and clarity'],
    usage: 'Eaten as a culinary mushroom or taken as a supplement.',
    precautions: 'Very safe, but avoid if you have mushroom allergies.',
    image: 'https://images.unsplash.com/photo-1626700051175-6818013e184f?q=80&w=800&auto=format&fit=crop',
    scientificBacking: 'Contains two compounds, hericenones and erinacines, that can stimulate the production of Nerve Growth Factor (NGF).',
  },
  {
    id: '46',
    name: 'Cordyceps',
    scientificName: 'Cordyceps militaris',
    category: 'Energy',
    description: 'A medicinal fungus known for boosting athletic performance and respiratory health.',
    benefits: ['Increases ATP production', 'Improves oxygen use', 'Anti-aging', 'Supports kidneys'],
    usage: 'Available in powders and capsules.',
    precautions: 'May interact with blood-thinning or diabetic medications.',
    image: 'https://images.unsplash.com/photo-1596040033229-a9821ebd058d?q=80&w=800&auto=format&fit=crop',
    scientificBacking: 'Studies show that cordyceps can increase the body’s production of the molecule adenosine triphosphate (ATP), which is essential for delivering energy to the muscles.',
  },
  {
    id: '47',
    name: 'Chaga',
    scientificName: 'Inonotus obliquus',
    category: 'Immune Support',
    description: 'A mushroom that grows on birch trees, packed with some of the highest antioxidant levels in the world.',
    benefits: ['Immune support', 'Extremely high antioxidants', 'Fights inflammation', 'Lower blood sugar'],
    usage: 'Traditionally brewed as a long-steeped tea.',
    precautions: 'High in oxalates; use caution if you have kidney issues.',
    image: 'https://images.unsplash.com/photo-1500382017468-9049fed747ef?q=80&w=800&auto=format&fit=crop',
    scientificBacking: 'Chaga has been shown to reduce cytokine production, which can help control inflammation and fight harmful bacteria and viruses.',
  },
  {
    id: '48',
    name: 'Burdock Root',
    scientificName: 'Arctium lappa',
    category: 'Detox',
    description: 'A powerhouse root used to cleanse the blood and treat skin conditions like acne and eczema.',
    benefits: ['Blood purifier', 'Diuretic', 'Heals skin issues', 'Digestive support'],
    usage: 'Eaten as a vegetable (Gobo) or taken as a decoction.',
    precautions: 'Diuretic effects can lead to dehydration if water intake is low.',
    image: 'https://images.unsplash.com/photo-1533282960533-51328aa49826?q=80&w=800&auto=format&fit=crop',
    scientificBacking: 'Research has found that burdock root contains multiple types of powerful antioxidants, including quercetin, luteolin, and phenolic acids.',
  },
  {
    id: '49',
    name: 'Butcher’s Broom',
    scientificName: 'Ruscus aculeatus',
    category: 'Circulation',
    description: 'Used for thousands of years to treat circulatory issues and reduce leg swelling.',
    benefits: ['Improves vein health', 'Reduces swelling', 'Anti-inflammatory', 'Mild laxative'],
    usage: 'Taken as an extract, often standardized to ruscogenins.',
    precautions: 'May cause stomach upset or nausea in some individuals.',
    image: 'https://images.unsplash.com/photo-1515471209610-dae1c9a581c5?q=80&w=800&auto=format&fit=crop',
    scientificBacking: 'Compounds called ruscogenins help cause the blood vessels to contract, which increases blood flow and prevents blood from pooling in the veins.',
  },
  {
    id: '50',
    name: 'Cat’s Claw',
    scientificName: 'Uncaria tomentosa',
    category: 'Immune Support',
    description: 'A woody vine from the Amazon rainforest, named for its claw-shaped thorns.',
    benefits: ['Immune stimulant', 'Reduces arthritis pain', 'DNA repair', 'Digestive health'],
    usage: 'Inner bark is used in teas or capsules.',
    precautions: 'Avoid if you have autoimmune diseases or are about to undergo an organ transplant.',
    image: 'https://images.unsplash.com/photo-1599940824399-b87987ceb72a?q=80&w=800&auto=format&fit=crop',
    scientificBacking: 'Studies suggest Cat’s Claw can stimulate the immune system and may even help repair DNA damaged by chemotherapy or ultraviolet radiation.',
  },
  {
    id: '51',
    name: 'Brahmi',
    scientificName: 'Bacopa monnieri',
    category: 'Cognitive',
    description: 'Brahmi is one of the most powerful brain tonics in Ayurvedic medicine.',
    benefits: ['Enhances memory', 'Focus and clarity', 'Reduces stress', 'Anti-aging for brain'],
    usage: 'Usually taken as a powder or extract with healthy fats.',
    precautions: 'May cause mild stomach upset if taken on an empty stomach.',
    image: 'https://images.unsplash.com/photo-1626700051175-6818013e184f?q=80&w=800&auto=format&fit=crop',
    scientificBacking: 'Studies suggest it increases the length of dendrites in the brain, improving communication between neurons.',
  },
  {
    id: '52',
    name: 'Borage',
    scientificName: 'Borago officinalis',
    category: 'Anti-inflammatory',
    description: 'Borage is an annual herb. Its flowers and leaves, as well as the oil from its seeds, are used as medicine.',
    benefits: ['Healthy skin', 'Hormonal balance', 'Anti-inflammatory', 'Relieves cough'],
    usage: 'Seed oil is typically used; leaves can be eaten in salads.',
    precautions: 'Contains pyrrolizidine alkaloids (PAs), which can be toxic to the liver; use only PA-free products.',
    image: 'https://images.unsplash.com/photo-1626700051175-6818013e184f?q=80&w=800&auto=format&fit=crop',
    scientificBacking: 'Borage seed oil is a rich source of gamma-linolenic acid (GLA), which has potent anti-inflammatory properties.',
  },
  {
    id: '53',
    name: 'Calendula',
    scientificName: 'Calendula officinalis',
    category: 'Skin Health',
    description: 'Often called "pot marigold," calendula is used for its powerful healing and anti-inflammatory effects on the skin.',
    benefits: ['Heals wounds', 'Soothes eczema', 'Antiseptic', 'Reduces muscle spasms'],
    usage: 'Topical creams, oils, or as a soothing tea.',
    precautions: 'Safe for most, but avoid if allergic to the Asteraceae family.',
    image: 'https://images.unsplash.com/photo-1596040033229-a9821ebd058d?q=80&w=800&auto=format&fit=crop',
    scientificBacking: 'Clinical trials show calendula to be effective in healing radiation-induced dermatitis.',
  },
  {
    id: '54',
    name: 'Cascara Sagrada',
    scientificName: 'Frangula purshiana',
    category: 'Digestive',
    description: 'Derived from the bark of a tree, it is a powerful natural laxative.',
    benefits: ['Relieves constipation', 'Detoxifies colon', 'Supports liver', 'Gallbladder health'],
    usage: 'Taken as a supplement or liquid extract; only use for short periods.',
    precautions: 'Do not use for more than 7 days; can cause electrolyte imbalance.',
    image: 'https://images.unsplash.com/photo-1515699503431-22bbf5ef1118?q=80&w=800&auto=format&fit=crop',
    scientificBacking: 'The anthraquinones in the bark stimulate peristalsis, the muscle contractions that move waste through the colon.',
  },
  {
    id: '55',
    name: 'Cramp Bark',
    scientificName: 'Viburnum opulus',
    category: 'Womens Health',
    description: 'As the name suggests, this herb is primarily used for its ability to relieve smooth muscle cramps.',
    benefits: ['Relieves menstrual cramps', 'Muscle relaxant', 'Nervous system tonic', 'Supports kidneys'],
    usage: 'Bark is used in decoctions or tinctures.',
    precautions: 'Relatively safe, but excessive amounts can cause stomach upset.',
    image: 'https://images.unsplash.com/photo-1500382017468-9049fed747ef?q=80&w=800&auto=format&fit=crop',
    scientificBacking: 'Contains valeric acid, which has antispasmodic properties that help relax the uterus.',
  },
  {
    id: '56',
    name: 'Damiana',
    scientificName: 'Turnera diffusa',
    category: 'Energy',
    description: 'A shrub native to Mexico and Central America, used as an aphrodisiac and tonic.',
    benefits: ['Boosts libido', 'Mood elevator', 'Increases energy', 'Supports digestion'],
    usage: 'Leaves are brewed as tea or used in tinctures.',
    precautions: 'May affect blood sugar levels; use caution with diabetes.',
    image: 'https://images.unsplash.com/photo-1533282960533-51328aa49826?q=80&w=800&auto=format&fit=crop',
    scientificBacking: 'Traditional use for libido is supported by compounds that increase oxygen delivery to genital areas.',
  },
  {
    id: '57',
    name: 'Dong Quai',
    scientificName: 'Angelica sinensis',
    category: 'Womens Health',
    description: 'Known as "female ginseng," it is used to balance hormones and improve blood quality.',
    benefits: ['Hormonal balance', 'Relieves PMS', 'Supports circulation', 'Skin health'],
    usage: 'Root is used in soups or as a supplement.',
    precautions: 'Can increase skin sensitivity to the sun; avoid during pregnancy.',
    image: 'https://images.unsplash.com/photo-1515471209610-dae1c9a581c5?q=80&w=800&auto=format&fit=crop',
    scientificBacking: 'Research shows it can help dilate blood vessels and relax the smooth muscles of the uterus.',
  },
  {
    id: '58',
    name: 'Eyebright',
    scientificName: 'Euphrasia',
    category: 'Vision Health',
    description: 'An herb used since the Middle Ages for all kinds of eye-related ailments.',
    benefits: ['Soothes eye irritation', 'Reduces inflammation', 'Rich in antioxidants', 'Supports sinus health'],
    usage: 'Used as an eye wash (sterilized) or taken as a tea.',
    precautions: 'Never use home-made eye washes; only use sterilized commercial products.',
    image: 'https://images.unsplash.com/photo-1599940824399-b87987ceb72a?q=80&w=800&auto=format&fit=crop',
    scientificBacking: 'Contains tannins and flavonoids that have strong anti-inflammatory properties.',
  },
  {
    id: '59',
    name: 'Feverfew',
    scientificName: 'Tanacetum parthenium',
    category: 'Pain Relief',
    description: 'A flowering plant used traditionally to reduce fevers and prevent migraine headaches.',
    benefits: ['Migraine prevention', 'Reduces fever', 'Anti-inflammatory', 'Relieves arthritis'],
    usage: 'Fresh or dried leaves are eaten or taken in capsules.',
    precautions: 'Chewing fresh leaves can cause mouth sores; capsules are preferred.',
    image: 'https://images.unsplash.com/photo-1596708027732-261ba1019036?q=80&w=800&auto=format&fit=crop',
    scientificBacking: 'Parthenolide in feverfew helps prevent the constriction of blood vessels in the brain.',
  },
  {
    id: '60',
    name: 'Goldenseal',
    scientificName: 'Hydrastis canadensis',
    category: 'Antimicrobial',
    description: 'A forest-growing plant prized for its powerful antimicrobial and immune-supporting root.',
    benefits: ['Natural antibiotic', 'Soothes mucous membranes', 'Immune booster', 'Digestive support'],
    usage: 'Powdered root in capsules or liquid tinctures.',
    precautions: 'Do not use long-term; can affect the absorption of B vitamins.',
    image: 'https://images.unsplash.com/photo-1626700051175-6818013e184f?q=80&w=800&auto=format&fit=crop',
    scientificBacking: 'Contains berberine, which has been shown to kill many types of bacteria and fungi.',
  },
  {
    id: '61',
    name: 'Hops',
    scientificName: 'Humulus lupulus',
    category: 'Sleep',
    description: 'Best known for its use in beer, hops have been used for centuries for their sedative properties.',
    benefits: ['Promotes sleep', 'Reduces anxiety', 'Supports digestion', 'Antispasmodic'],
    usage: 'Brewed as tea or taken in capsules; often paired with valerian.',
    precautions: 'Avoid if you have depression, as it may have a depressive effect.',
    image: 'https://images.unsplash.com/photo-1596040033229-a9821ebd058d?q=80&w=800&auto=format&fit=crop',
    scientificBacking: 'The resins in hops help regulate GABA receptors in the brain, inducing calmness.',
  },
  {
    id: '62',
    name: 'Horse Chestnut',
    scientificName: 'Aesculus hippocastanum',
    category: 'Circulation',
    description: 'The seeds of this tree are a classic remedy for venous insufficiency and varicose veins.',
    benefits: ['Supports veins', 'Reduces swelling', 'Anti-inflammatory', 'Rich in antioxidants'],
    usage: 'Seed extract in capsules or topical creams.',
    precautions: 'Raw seeds are toxic; only use processed commercial extracts.',
    image: 'https://images.unsplash.com/photo-1500382017468-9049fed747ef?q=80&w=800&auto=format&fit=crop',
    scientificBacking: 'Escin in the seeds helps strengthen the walls of veins and capillaries.',
  },
  {
    id: '63',
    name: 'Juniper Berries',
    scientificName: 'Juniperus communis',
    category: 'Urinary Health',
    description: 'The "berries" are actually small cones, used for their antiseptic and diuretic properties.',
    benefits: ['Urinary antiseptic', 'Digestive aid', 'Antioxidant', 'Anti-inflammatory'],
    usage: 'Dried berries in tea or culinary uses.',
    precautions: 'Not for use during pregnancy or by those with kidney disease.',
    image: 'https://images.unsplash.com/photo-1533282960533-51328aa49826?q=80&w=800&auto=format&fit=crop',
    scientificBacking: 'Volatile oils in the berries stimulate the kidneys and have strong antimicrobial activity.',
  },
  {
    id: '64',
    name: 'Lobelia',
    scientificName: 'Lobelia inflata',
    category: 'Respiratory',
    description: 'Also called "Indian Tobacco," it is used primarily for its effects on the respiratory and nervous systems.',
    benefits: ['Clears lungs', 'Relaxes muscles', 'Aids smoking cessation', 'Nerve tonic'],
    usage: 'Tincture or very dilute tea; use under professional guidance.',
    precautions: 'High doses can cause vomiting and severe nausea; use with extreme caution.',
    image: 'https://images.unsplash.com/photo-1515471209610-dae1c9a581c5?q=80&w=800&auto=format&fit=crop',
    scientificBacking: 'Contains lobeline, which mimics the effects of nicotine on certain receptors.',
  },
  {
    id: '65',
    name: 'Lomatium',
    scientificName: 'Lomatium dissectum',
    category: 'Antimicrobial',
    description: 'A desert parsley root used for its powerful antiviral and antibacterial properties.',
    benefits: ['Strong antiviral', 'Clears respiratory infections', 'Supports immune system', 'Antiseptic'],
    usage: 'Usually taken as a tincture; it has a very strong, distinct taste.',
    precautions: 'Can cause a temporary, non-dangerous full-body skin rash in some people.',
    image: 'https://images.unsplash.com/photo-1515471209610-dae1c9a581c5?q=80&w=800&auto=format&fit=crop',
    scientificBacking: 'Was famously used during the 1918 flu pandemic with remarkable success in preventing secondary pneumonia.',
  },
  {
    id: '66',
    name: 'Motherwort',
    scientificName: 'Leonurus cardiaca',
    category: 'Heart Health',
    description: 'The "lion-hearted" herb, motherwort is used for both the emotional and physical heart.',
    benefits: ['Calms heart palpitations', 'Reduces anxiety', 'Regulates menstrual cycles', 'Lower blood pressure'],
    usage: 'Tincture or tea; it has a very bitter taste.',
    precautions: 'Do not use during pregnancy as it may cause contractions.',
    image: 'https://images.unsplash.com/photo-1596708027732-261ba1019036?q=80&w=800&auto=format&fit=crop',
    scientificBacking: 'Alkaloids in motherwort have a mild sedative effect on the cardiovascular system.',
  },
  {
    id: '67',
    name: 'Pau d’Arco',
    scientificName: 'Handroanthus impetiginosus',
    category: 'Antimicrobial',
    description: 'The inner bark of this Amazonian tree is a powerhouse antifungal and immune booster.',
    benefits: ['Fights yeast/Candida', 'Immune support', 'Anti-inflammatory', 'Rich in antioxidants'],
    usage: 'Inner bark is simmered into a strong tea.',
    precautions: 'Avoid if taking blood thinners.',
    image: 'https://images.unsplash.com/photo-1626700051175-6818013e184f?q=80&w=800&auto=format&fit=crop',
    scientificBacking: 'Contains lapachol, which has been found to have antimicrobial and antiviral effects.',
  },
  {
    id: '68',
    name: 'Red Clover',
    scientificName: 'Trifolium pratense',
    category: 'Womens Health',
    description: 'A flowering plant used to treat menopause symptoms and cleanse the blood.',
    benefits: ['Relieves hot flashes', 'Supports bone health', 'Blood purifier', 'Skin support'],
    usage: 'Flowering tops are used in teas and tinctures.',
    precautions: 'Contains phytoestrogens; use caution with hormone-sensitive conditions.',
    image: 'https://images.unsplash.com/photo-1596040033229-a9821ebd058d?q=80&w=800&auto=format&fit=crop',
    scientificBacking: 'Rich in isoflavones, which can mimic the effects of estrogen in the body.',
  },
  {
    id: '69',
    name: 'Skullcap',
    scientificName: 'Scutellaria lateriflora',
    category: 'Calming',
    description: 'A favorite of herbalists for its ability to calm "monkey mind" and nervous tension.',
    benefits: ['Reduces anxiety', 'Promotes sleep', 'Muscle relaxant', 'Nerve tonic'],
    usage: 'Best used as a fresh plant tincture or tea.',
    precautions: 'Very safe, but ensure you have the correct species (American Skullcap).',
    image: 'https://images.unsplash.com/photo-1500382017468-9049fed747ef?q=80&w=800&auto=format&fit=crop',
    scientificBacking: 'Has been shown to have anxiolytic activity in humans, likely through GABA receptor interaction.',
  },
  {
    id: '70',
    name: 'Thyme',
    scientificName: 'Thymus vulgaris',
    category: 'Respiratory',
    description: 'More than just a kitchen herb, thyme is a powerful respiratory and immune support.',
    benefits: ['Clears coughs', 'Antimicrobial', 'Antispasmodic', 'Immune booster'],
    usage: 'Culinary, tea, or as an essential oil (diluted).',
    precautions: 'Essential oil should never be ingested without professional guidance.',
    image: 'https://images.unsplash.com/photo-1533282960533-51328aa49826?q=80&w=800&auto=format&fit=crop',
    scientificBacking: 'Thymol and carvacrol in thyme are potent antibacterial agents.',
  },
  {
    id: '71',
    name: 'Vitex (Chasteberry)',
    scientificName: 'Vitex agnus-castus',
    category: 'Womens Health',
    description: 'The premier herb for balancing the female reproductive system.',
    benefits: ['Relieves PMS', 'Balances progesterone', 'Improves fertility', 'Acne support'],
    usage: 'Best taken in the morning as a capsule or tincture.',
    precautions: 'Takes 3-6 months to see full effects; avoid during pregnancy.',
    image: 'https://images.unsplash.com/photo-1515471209610-dae1c9a581c5?q=80&w=800&auto=format&fit=crop',
    scientificBacking: 'Influences the pituitary gland to increase luteinizing hormone and reduce prolactin.',
  },
  {
    id: '72',
    name: 'Witch Hazel',
    scientificName: 'Hamamelis virginiana',
    category: 'Skin Health',
    description: 'A staple in skin care, known for its powerful astringent properties.',
    benefits: ['Tightens skin', 'Reduces hemorrhoids', 'Soothes acne', 'Anti-inflammatory'],
    usage: 'Applied topically as a distilled extract.',
    precautions: 'Should not be taken internally in large amounts.',
    image: 'https://images.unsplash.com/photo-1599940824399-b87987ceb72a?q=80&w=800&auto=format&fit=crop',
    scientificBacking: 'High tannin content causes tissues to contract and reduce swelling.',
  },
  {
    id: '73',
    name: 'Yarrow',
    scientificName: 'Achillea millefolium',
    category: 'First Aid',
    description: 'A ancient wound-healing herb used to stop bleeding and fight infections.',
    benefits: ['Stops bleeding', 'Lower fever', 'Supports digestion', 'Anti-inflammatory'],
    usage: 'Topical for wounds; tea for fevers and digestion.',
    precautions: 'May cause allergic skin reactions in some individuals.',
    image: 'https://images.unsplash.com/photo-1596708027732-261ba1019036?q=80&w=800&auto=format&fit=crop',
    scientificBacking: 'Contains achilleine, which helps promote blood clotting.',
  },
  {
    id: '74',
    name: 'Yerba Santa',
    scientificName: 'Eriodictyon californicum',
    category: 'Respiratory',
    description: 'The "holy herb" used by Native Americans for respiratory issues.',
    benefits: ['Expectorant', 'Breaks up mucus', 'Treats asthma', 'Antimicrobial'],
    usage: 'Leaves are chewed or brewed as tea.',
    precautions: 'Can be quite drying to the mucous membranes.',
    image: 'https://images.unsplash.com/photo-1626700051175-6818013e184f?q=80&w=800&auto=format&fit=crop',
    scientificBacking: 'Resins in the leaves have a potent effect on clearing respiratory congestion.',
  },
  {
    id: '75',
    name: 'Plantain',
    scientificName: 'Plantago major',
    category: 'First Aid',
    description: 'Not the banana-like fruit! This common weed is one of the best skin-healing herbs.',
    benefits: ['Draws out stingers/venom', 'Heals skin rashes', 'Anti-inflammatory', 'Supports digestion'],
    usage: 'Fresh leaf poultice for skin; tea for internal use.',
    precautions: 'Very safe; commonly found in backyards.',
    image: 'https://images.unsplash.com/photo-1596040033229-a9821ebd058d?q=80&w=800&auto=format&fit=crop',
    scientificBacking: 'Contains aucubin and allantoin, which promote tissue regeneration and wound healing.',
  },
  {
    id: '76',
    name: 'Artichoke Leaf',
    scientificName: 'Cynara cardunculus',
    category: 'Digestive',
    description: 'Artichoke leaf extract is used to stimulate bile production and support liver health.',
    benefits: ['Supports digestion', 'Lower cholesterol', 'Liver detox', 'Rich in antioxidants'],
    usage: 'Available as a supplement or liquid extract.',
    precautions: 'Avoid if you have gallstones or a bile duct obstruction.',
    image: 'https://images.unsplash.com/photo-1515699503431-22bbf5ef1118?q=80&w=800&auto=format&fit=crop',
    scientificBacking: 'Cynarin in artichoke leaf increases bile flow, which helps break down fats and protect the liver.',
  },
  {
    id: '77',
    name: 'Black Cohosh',
    scientificName: 'Actaea racemosa',
    category: 'Womens Health',
    description: 'Native to North America, it is a leading herb for menopause symptoms.',
    benefits: ['Relieves hot flashes', 'Supports sleep during menopause', 'Mood balance', 'Joint health'],
    usage: 'Root is used in capsules or tinctures.',
    precautions: 'Do not use during pregnancy; can affect the liver in rare cases.',
    image: 'https://images.unsplash.com/photo-1500382017468-9049fed747ef?q=80&w=800&auto=format&fit=crop',
    scientificBacking: 'Acts on neurotransmitters in the brain to help regulate body temperature.',
  },
  {
    id: '78',
    name: 'Cilantro',
    scientificName: 'Coriandrum sativum',
    category: 'Detox',
    description: 'More than a garnish, cilantro is known for its ability to bind to heavy metals.',
    benefits: ['Heavy metal detox', 'Digestive support', 'Antioxidant', 'Antimicrobial'],
    usage: 'Eat fresh in large quantities or use as a concentrated tincture.',
    precautions: 'Safe for most, but some people find the taste soapy due to genetics.',
    image: 'https://images.unsplash.com/photo-1515471209610-dae1c9a581c5?q=80&w=800&auto=format&fit=crop',
    scientificBacking: 'Some animal studies suggest cilantro can help the body excrete heavy metals like lead and mercury.',
  },
  {
    id: '79',
    name: 'Comfrey',
    scientificName: 'Symphytum officinale',
    category: 'First Aid',
    description: 'Also called "knitbone," comfrey is used to heal skin and bones.',
    benefits: ['Heals broken bones', 'Soothes skin rashes', 'Anti-inflammatory', 'Cell regenerator'],
    usage: 'Used strictly as a topical poultice, ointment, or oil.',
    precautions: 'DO NOT ingest; contains alkaloids that are toxic to the liver.',
    image: 'https://images.unsplash.com/photo-1599940824399-b87987ceb72a?q=80&w=800&auto=format&fit=crop',
    scientificBacking: 'Allantoin in comfrey speeds up skin healing and bone knitting by stimulating cell growth.',
  },
  {
    id: '80',
    name: 'Devil’s Claw',
    scientificName: 'Harpagophytum procumbens',
    category: 'Pain Relief',
    description: 'An African plant named for its hook-like fruit, used for inflammatory pain.',
    benefits: ['Arthritis relief', 'Back pain support', 'Anti-inflammatory', 'Digestive aid'],
    usage: 'Secondary roots are ground into powder for capsules.',
    precautions: 'May interact with blood thinners and stomach acid medications.',
    image: 'https://images.unsplash.com/photo-1596708027732-261ba1019036?q=80&w=800&auto=format&fit=crop',
    scientificBacking: 'Contains harpagosides, which have significant anti-inflammatory and analgesic effects.',
  },
  {
    id: '81',
    name: 'Eleuthero (Siberian Ginseng)',
    scientificName: 'Eleutherococcus senticosus',
    category: 'Adaptogen',
    description: 'A classic adaptogen used by cosmonauts and athletes to improve endurance.',
    benefits: ['Stress resistance', 'Immune support', 'Boosts energy', 'Improves focus'],
    usage: 'Root is taken as a capsule, tincture, or tea.',
    precautions: 'May cause insomnia if taken too late in the day.',
    image: 'https://images.unsplash.com/photo-1626700051175-6818013e184f?q=80&w=800&auto=format&fit=crop',
    scientificBacking: 'Helps the body regulate cortisol and improves oxygen uptake during exercise.',
  },
  {
    id: '82',
    name: 'Gentian Root',
    scientificName: 'Gentiana lutea',
    category: 'Digestive',
    description: 'The king of bitter herbs, used to jump-start the digestive process.',
    benefits: ['Stimulates appetite', 'Aids digestion', 'Supports liver', 'Anti-inflammatory'],
    usage: 'Taken as a tincture/bitters before meals.',
    precautions: 'Extremely bitter; avoid if you have stomach ulcers.',
    image: 'https://images.unsplash.com/photo-1596040033229-a9821ebd058d?q=80&w=800&auto=format&fit=crop',
    scientificBacking: 'Bitter compounds trigger a reflex that increases saliva and gastric secretions.',
  },
  {
    id: '83',
    name: 'Gymnema Sylvestre',
    scientificName: 'Gymnema sylvestre',
    category: 'Metabolic Support',
    description: 'Known as the "sugar destroyer," it helps balance blood sugar and reduce cravings.',
    benefits: ['Lower blood sugar', 'Reduces sugar cravings', 'Weight management', 'Heart health'],
    usage: 'Leaves are chewed or taken as a capsule/tea.',
    precautions: 'Use caution if already taking insulin or other diabetes medications.',
    image: 'https://images.unsplash.com/photo-1500382017468-9049fed747ef?q=80&w=800&auto=format&fit=crop',
    scientificBacking: 'Gymnemic acids block the receptors for sweetness on the tongue and in the intestines.',
  },
  {
    id: '84',
    name: 'Hyssop',
    scientificName: 'Hyssopus officinalis',
    category: 'Respiratory',
    description: 'A sacred herb used since biblical times for purification and respiratory health.',
    benefits: ['Expectorant', 'Antiviral', 'Digestive support', 'Soothes skin'],
    usage: 'Leaves and flowers used in teas or steam inhalations.',
    precautions: 'Essential oil can be neurotoxic in high doses; use with care.',
    image: 'https://images.unsplash.com/photo-1533282960533-51328aa49826?q=80&w=800&auto=format&fit=crop',
    scientificBacking: 'Contains volatile oils that help loosen mucus in the lungs.',
  },
  {
    id: '85',
    name: 'Mugwort',
    scientificName: 'Artemisia vulgaris',
    category: 'Digestive',
    description: 'A versatile herb used for dreaming, digestion, and female reproductive health.',
    benefits: ['Aids digestion', 'Lucid dreaming', 'Regulates menses', 'Nerve tonic'],
    usage: 'Leaves are used in tea or as a smoke/incense.',
    precautions: 'Do not use during pregnancy; can cause miscarriage.',
    image: 'https://images.unsplash.com/photo-1515471209610-dae1c9a581c5?q=80&w=800&auto=format&fit=crop',
    scientificBacking: 'Contains thujone, which has effects on the nervous system.',
  },
  {
    id: '86',
    name: 'Oat Straw',
    scientificName: 'Avena sativa',
    category: 'Calming',
    description: 'Derived from the green stems of the oat plant, it is the ultimate food for the nervous system.',
    benefits: ['Nourishes nerves', 'Reduces anxiety', 'Rich in minerals', 'Skin support'],
    usage: 'Brewed as a strong infusion (tea).',
    precautions: 'Very safe; avoid if you have severe gluten sensitivity.',
    image: 'https://images.unsplash.com/photo-1599940824399-b87987ceb72a?q=80&w=800&auto=format&fit=crop',
    scientificBacking: 'High in calcium, magnesium, and silica, essential for nerve health.',
  },
  {
    id: '87',
    name: 'Pleurisy Root',
    scientificName: 'Asclepias tuberosa',
    category: 'Respiratory',
    description: 'A species of milkweed used specifically for inflammation of the lungs.',
    benefits: ['Clears congestion', 'Lower fever', 'Reduces lung pain', 'Expectorant'],
    usage: 'Root used in decoctions or tinctures.',
    precautions: 'High doses can cause nausea; do not use during pregnancy.',
    image: 'https://images.unsplash.com/photo-1596708027732-261ba1019036?q=80&w=800&auto=format&fit=crop',
    scientificBacking: 'Contains compounds that help improve circulation in the lungs and reduce irritation.',
  },
  {
    id: '88',
    name: 'Quassia',
    scientificName: 'Quassia amara',
    category: 'Digestive',
    description: 'One of the most bitter substances on earth, used for digestion and parasites.',
    benefits: ['Digestive bitter', 'Kills parasites', 'Rich in antioxidants', 'Liver support'],
    usage: 'Tincture or very dilute tea.',
    precautions: 'Avoid during pregnancy and if you have irritable bowel issues.',
    image: 'https://images.unsplash.com/photo-1626700051175-6818013e184f?q=80&w=800&auto=format&fit=crop',
    scientificBacking: 'Contains quassinoids that have potent anti-parasitic properties.',
  },
  {
    id: '89',
    name: 'Rhubarb Root',
    scientificName: 'Rheum palmatum',
    category: 'Digestive',
    description: 'Not the culinary stalk! The medicinal root is used as a potent laxative.',
    benefits: ['Relieves constipation', 'Detoxifies colon', 'Antibacterial', 'Anti-inflammatory'],
    usage: 'Powdered root in capsules or tinctures.',
    precautions: 'Can cause cramping; do not use long-term.',
    image: 'https://images.unsplash.com/photo-1596040033229-a9821ebd058d?q=80&w=800&auto=format&fit=crop',
    scientificBacking: 'Anthraquinones stimulate the colon muscles to move waste.',
  },
  {
    id: '90',
    name: 'Sarsaparilla',
    scientificName: 'Smilax ornata',
    category: 'Skin Health',
    description: 'Used for centuries to treat skin conditions and as an overall tonic.',
    benefits: ['Clears psoriasis', 'Hormonal balance', 'Anti-inflammatory', 'Kidney support'],
    usage: 'Root used in decoctions or tinctures.',
    precautions: 'May cause stomach irritation in high doses.',
    image: 'https://images.unsplash.com/photo-1515699503431-22bbf5ef1118?q=80&w=800&auto=format&fit=crop',
    scientificBacking: 'Saponins help bind to toxins in the blood and remove them from the body.',
  },
  {
    id: '91',
    name: 'Shepherd’s Purse',
    scientificName: 'Capsella bursa-pastoris',
    category: 'First Aid',
    description: 'A common weed used specifically to stop external and internal bleeding.',
    benefits: ['Hemostatic', 'Regulates heavy menses', 'Supports bladder', 'Lower blood pressure'],
    usage: 'Fresh plant tincture or tea.',
    precautions: 'Do not use if you have kidney stones or during pregnancy.',
    image: 'https://images.unsplash.com/photo-1500382017468-9049fed747ef?q=80&w=800&auto=format&fit=crop',
    scientificBacking: 'Contains a peptide that acts as a vasoconstrictor to stop bleeding.',
  },
  {
    id: '92',
    name: 'Tansy',
    scientificName: 'Tanacetum vulgare',
    category: 'Parasite Cleanse',
    description: 'A powerful herb used traditionally to expel worms and parasites.',
    benefits: ['Anthelmintic', 'Digestive aid', 'Treats skin sores', 'Repels insects'],
    usage: 'Used as tea or oil (external only); use internal under strict guidance.',
    precautions: 'HIGHLY toxic in large amounts; use extreme caution.',
    image: 'https://images.unsplash.com/photo-1533282960533-51328aa49826?q=80&w=800&auto=format&fit=crop',
    scientificBacking: 'Contains thujone, which is effective against intestinal parasites.',
  },
  {
    id: '93',
    name: 'Usnea',
    scientificName: 'Usnea barbata',
    category: 'Antimicrobial',
    description: 'A lichen that grows on trees, often called "Old Man’s Beard."',
    benefits: ['Natural antibiotic', 'Fights yeast', 'Immune support', 'Respiratory health'],
    usage: 'Tincture is the best way to extract the usnic acid.',
    precautions: 'Avoid high doses for long periods; may affect the liver.',
    image: 'https://images.unsplash.com/photo-1515471209610-dae1c9a581c5?q=80&w=800&auto=format&fit=crop',
    scientificBacking: 'Usnic acid is a potent antibacterial agent, particularly against Gram-positive bacteria.',
  },
  {
    id: '94',
    name: 'White Willow Bark',
    scientificName: 'Salix alba',
    category: 'Pain Relief',
    description: 'The original source of aspirin, used for thousands of years for pain.',
    benefits: ['Natural aspirin', 'Reduces fever', 'Anti-inflammatory', 'Joint pain relief'],
    usage: 'Bark used in tea or capsules.',
    precautions: 'Do not give to children (Reye’s syndrome); avoid if allergic to aspirin.',
    image: 'https://images.unsplash.com/photo-1599940824399-b87987ceb72a?q=80&w=800&auto=format&fit=crop',
    scientificBacking: 'Contains salicin, which the body converts into salicylic acid (the precursor to aspirin).',
  },
  {
    id: '95',
    name: 'Wild Cherry Bark',
    scientificName: 'Prunus serotina',
    category: 'Respiratory',
    description: 'A classic cough-syrup ingredient used to quiet annoying dry coughs.',
    benefits: ['Antitussive', 'Expectorant', 'Digestive aid', 'Sedative'],
    usage: 'Inner bark is used in syrups and teas.',
    precautions: 'Do not use long-term; contains trace amounts of cyanide compounds.',
    image: 'https://images.unsplash.com/photo-1596708027732-261ba1019036?q=80&w=800&auto=format&fit=crop',
    scientificBacking: 'Helps depress the cough reflex and relax the respiratory muscles.',
  },
  {
    id: '96',
    name: 'Wood Betony',
    scientificName: 'Stachys officinalis',
    category: 'Calming',
    description: 'A grounding herb used to pull energy from the head and soothe tension.',
    benefits: ['Relieves headaches', 'Anxiety support', 'Digestive aid', 'Grounding effect'],
    usage: 'Leaves used in tea or tinctures.',
    precautions: 'Generally safe, but may cause low blood pressure in some.',
    image: 'https://images.unsplash.com/photo-1626700051175-6818013e184f?q=80&w=800&auto=format&fit=crop',
    scientificBacking: 'Traditional use for tension headaches is supported by its mild sedative and anti-inflammatory properties.',
  },
  {
    id: '97',
    name: 'Yellow Gentian',
    scientificName: 'Gentiana lutea',
    category: 'Digestive',
    description: 'A primary ingredient in many traditional digestive bitters.',
    benefits: ['Boosts digestion', 'Increases bile', 'Lower fever', 'Supports liver'],
    usage: 'Root taken as tincture before meals.',
    precautions: 'Do not use if you have high blood pressure or ulcers.',
    image: 'https://images.unsplash.com/photo-1596040033229-a9821ebd058d?q=80&w=800&auto=format&fit=crop',
    scientificBacking: 'Stimulates the bitter receptors on the tongue, triggering digestive enzyme release.',
  },
  {
    id: '98',
    name: 'Yucca Root',
    scientificName: 'Yucca schidigera',
    category: 'Anti-inflammatory',
    description: 'A desert plant used to reduce joint inflammation and support digestion.',
    benefits: ['Arthritis support', 'Anti-inflammatory', 'Rich in saponins', 'Skin healing'],
    usage: 'Root taken as a supplement or applied topically.',
    precautions: 'Can cause stomach upset if taken in large quantities.',
    image: 'https://images.unsplash.com/photo-1500382017468-9049fed747ef?q=80&w=800&auto=format&fit=crop',
    scientificBacking: 'Saponins in yucca have anti-inflammatory and anti-protozoal effects.',
  },
  {
    id: '99',
    name: 'Zhi Mu',
    scientificName: 'Anemarrhena asphodeloides',
    category: 'Detox',
    description: 'A TCM herb used to "clear heat" and nourish the body’s fluids.',
    benefits: ['Reduces fever', 'Anti-diabetic', 'Anti-inflammatory', 'Moistening effect'],
    usage: 'Rhizome used in decoctions.',
    precautions: 'Avoid if you have chronic diarrhea or "weak" digestion.',
    image: 'https://images.unsplash.com/photo-1533282960533-51328aa49826?q=80&w=800&auto=format&fit=crop',
    scientificBacking: 'Studies show it can improve insulin sensitivity and lower blood glucose.',
  },
  {
    id: '100',
    name: 'Lemon Balm',
    scientificName: 'Melissa officinalis',
    category: 'Calming',
    description: 'A gentle herb from the mint family used to lift the mood and calm the mind.',
    benefits: ['Reduces anxiety', 'Antiviral', 'Improves sleep', 'Aids digestion'],
    usage: 'Leaves in tea, tinctures, or as an essential oil.',
    precautions: 'May affect thyroid medication; use with caution if hypothyroid.',
    image: 'https://images.unsplash.com/photo-1515471209610-dae1c9a581c5?q=80&w=800&auto=format&fit=crop',
    scientificBacking: 'Research indicates it inhibits the enzyme that breaks down GABA, maintaining a calm state.',
  },
];
